version: '3.8'

services:
  app:
    image: ghcr.io/thechrismoth/wolfybot/app:${TAG}
    build:
      context: ./app
      dockerfile: Dockerfile

  app-latest:
    image: ghcr.io/thechrismoth/wolfybot/app:latest
    build:
      context: ./app
      dockerfile: Dockerfile

  nginx:
    image: ghcr.io/thechrismoth/wolfybot/nginx:${TAG}
    build:
      context: ./nginx
      dockerfile: Dockerfile

  nginx-latest:
    image: ghcr.io/thechrismoth/wolfybot/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile