version: '3.8'

services:
  app:
    image: ghcr.io/thechrismoth/wolfybot/app:${TAG}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN=${TOKEN}
      - ID=${ID}
      - AITOKEN=${AITOKEN}
      - TZ=Europe/Moscow
    ports:
      - '8000:8000'
    restart: always

  nginx:
    image: ghcr.io/thechrismoth/wolfybot/nginx:${TAG}
    ports:
      - '80:80'
    depends_on:
      - app
    restart: always