services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TOKEN=${TOKEN}
      - ID=${ID}
      - AITOKEN=${AITOKEN}
      - TZ=Europe/Moscow
    ports:
      - '8000:8000'
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5438:5432'
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Подключаем созданный конфиг
    environment:
      - TZ=Europe/Moscow
    ports:
      - '80:80'  # Открываем порт 80 для внешнего доступа
    depends_on:
      - app
    restart: always

volumes:
  db_data: