version: '3.8'

services:
  app:
    image: ghcr.io/thechrismoth/wolfybot/app:${TAG}
    build:
      context: .
      dockerfile: ./app

  nginx:
    image: ghcr.io/thechrismoth/wolfybot/nginx:${TAG}
    build:
      context: .
      dockerfile: ./nginx