name: deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Шаг 3: Сборка и пушинг образа app
      - name: Build and push app image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app:latest ./app
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app:latest

      # Шаг 4: Сборка и пушинг образа nginx
      - name: Build and push nginx image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx:latest ./nginx
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # Шаг 5: Деплой на сервер
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Wolfybot
            # Логин в GitHub Container Registry
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            # Экспорт переменных окружения
            export DATABASE_URL='${{ secrets.DATABASE_URL }}'
            export TOKEN='${{ secrets.TOKEN }}'
            export ID='${{ secrets.ID }}'
            export AITOKEN='${{ secrets.AITOKEN }}'
            # Остановка и удаление старых контейнеров
            docker compose down
            # Скачивание новых образов
            docker compose pull
            # Запуск новых контейнеров
            docker compose up -d