name: Release CI/CD

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "ID=${{ secrets.ID }}" >> $GITHUB_ENV
          echo "AITOKEN=${{ secrets.AITOKEN }}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build and push using docker build
        run: |
          docker build -t ghcr.io/thechrismoth/wolfybot/app:$TAG ./app
          docker build -t ghcr.io/thechrismoth/wolfybot/nginx:$TAG ./nginx
          docker push ghcr.io/thechrismoth/wolfybot/app:$TAG
          docker push ghcr.io/thechrismoth/wolfybot/nginx:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Wolfybot
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export DATABASE_URL='${{ secrets.DATABASE_URL }}'
            export TOKEN='${{ secrets.TOKEN }}'
            export ID='${{ secrets.ID }}'
            export AITOKEN='${{ secrets.AITOKEN }}'
            export TAG=${{ github.event.release.tag_name }}
            echo "TAG=$TAG"
            docker compose down
            docker compose pull
            docker compose up -d
