name: deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          #key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/Wolfybot 
            git fetch origin
            git reset --hard origin/main
            /snap/bin/docker-compose up -d --build
